bookers2-debug/config/routes.rb
Rails.application.routes.draw do
  get 'groups/index'
  get 'groups/edit'
  get 'groups/show'
  get 'messages/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get "search" => "searches#search"

  resources :messages, only: [:create]
  get 'message/:id', to: 'messages#show', as: 'message'
  resources :rooms, only: [:create, :show]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers2-debug/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence:true
end

bookers2-debug/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = params[:comment]
    comment =current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find(params[:id]).destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

bookers2-debug/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2-debug/app/views/book_comments/_comment.html.erb
<div>
    <p>コメント件数：<%= book.book_comments.count %></p>
    <% book.book_comments.each do |book_comment| %>
      <p><%= image_tag book_comment.user.get_profile_image(64,64) %></p>
      <%= book_comment.user.name %>
      <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
      <% if book_comment.user == current_user %>
        <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
      <% end %>
    <% end %>
  </div>

bookers2-debug/app/views/book_comments/create.js.erb
$(".comment_<%= @book.id %>").html("<%= j(render 'book_comments/comment', book: @book) %>");
$("textarea").val('');

bookers2-debug/app/views/book_comments/destroy.js.erb
$(".comment_<%= @book.id %>").html("<%= j(render 'book_comments/comment', book: @book) %>");