bookers2-debug/config/routes.rb
Rails.application.routes.draw do
  get 'groups/index'
  get 'groups/edit'
  get 'groups/show'
  get 'messages/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get "search" => "searches#search"

  resources :messages, only: [:create]
  get 'message/:id', to: 'messages#show', as: 'message'
  resources :rooms, only: [:create, :show]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers2-debug/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :favorited_books, through: :favorites, source: :books

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy


  has_many :group_users   #ここ！
  has_many :groups, through: :group_users
  # has_many :owned_groups, class_name: "Group"


  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    relationships.find_by(follower_id: user.id).present?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

end

bookers2-debug/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @weekago_book = @books.created_weekago
    @twoweekago_book = @books.created_twoweekago
    @twoday_book = @books.created_twoday
    @threeday_book = @books.created_threeday
    @fourday_book = @books.created_fourday
    @fiveday_book = @books.created_fiveday
    @sixday_book = @books.created_sixday

    @week = @sixday_book, @fiveday_book, @fourday_book, @threeday_book, @twoday_book, @yesterday_book, @twoday_book
    @week_labels = "6日前", "5日前", "4日前", "3日前", "2日前", "1日前", "今日"

    # @book_by_day = @books.group_by_day(:created_at).size
    # @chartlabels = @book_by_day.map(&:first).to_json.html_safe
    # @chartdatas = @book_by_day.map(&:second)



  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(current_user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

bookers2-debug/app/helpers/users_helper.rb
module UsersHelper
end

bookers2-debug/app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers2-debug/app/views/users/_info.html.erb
<table class='table'>
  <tr>
    <th><%= image_tag user.get_profile_image(64,64) %></th>
    <th>
      <% if current_user == user %>
        <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
      <% else %>
        <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
        <% end %>
      <% end %>


      <% unless user.id == current_user.id %>
        <% if (current_user.following?(user)) && (user.following?(current_user)) %>
          <%= link_to 'Begin Chat', message_path(user.id) %>
        <% end %>
      <% end %>


    </th>
  </tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to user_followings_path(user) do %>
        <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to user_followers_path(user) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

bookers2-debug/app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

bookers2-debug/app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'users/index',users: @users %>
    </div>
  </div>
</div>

bookers2-debug/app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
    <div class = "table_width">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
            <th>今週の投稿数</th>
            <th>先週の投稿数</th>
            <th>先週比</th>
           </tr>
        </thead>
        <tbody>
          <tr>
     　      <td><%= @today_book.count %></td>
     　      <td><%= @yesterday_book.count %></td>
     　      <td>
               <% if @yesterday_book.count == 0 %>
                  前日の投稿はありません
               <% else %>
       　         <% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
       　         <%= (@the_day_before * 100).round %>
               <% end %>
            </td>

             <td><%= @weekago_book.count %></td>
     　      <td><%= @twoweekago_book.count %></td>
     　      <td>
               <% if @twoweekago_book.count == 0 %>
                  先週の投稿はありません
               <% else %>
       　         <% @the_week_before =   @weekago_book.count / @twoweekago_book.count.to_f  %>
       　         <%= (@the_week_before * 100).round %>
               <% end %>
            </td>
          </tr>
        </tbody>



        <table class="table table-bordered">
        <thead>
          <tr>
            <th>6日前</th>
            <th>5日前</th>
            <th>4日前</th>
            <th>3日前</th>
            <th>2日前</th>
            <th>1日前</th>
            <th>今日</th>
           </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @sixday_book.count %></td>
     　      <td><%= @fiveday_book.count %></td>
     　      <td><%= @fourday_book.count %></td>
     　      <td><%= @threeday_book.count %></td>
     　      <td><%= @twoday_book.count %></td>
     　      <td><%= @yesterday_book.count %></td>
     　      <td><%= @today_book.count %></td>
     　    </tr>
        </tbody>



        <canvas id="myChart" width="200" height="100"> </canvas>

        <script>
          var ctx = document.getElementById("myChart").getContext('2d');
          var myChart = new Chart(ctx, {
              type: 'bar',
              data: {
                  labels: <%= @week_labels %>,
                  datasets: [{
                      label: "日別投稿数",
                      data: <%= @week %>,
                      backgroundColor: 'rgba(255, 80, 120, 1.0)',
                      borderColor: 'rgba(255, 80, 120, 1.0)',
                      fill: false
                  }]
              },
          });
        </script>

      </table>
    </div>
  </div>
</div>